### ISSUE TITLE
[Feature Request] Installation Guide: Wiff Reader: Clearcore license path is not given

### ISSUE THREAD

**Issue by omaus** [CSBiology/MzIO#5]
**Is your feature request related to a problem? Please describe.**
Clearcore License path is not easy to find.

**Describe the solution you'd like**
Instead of 
> A dummy file for the license which can be replaced is already located at the correct position in the project.

the respective path would be easier to find and saves a lot of searching time for the user:

> A dummy file for the license which can be replaced is already located at `..\src\MzIO.Wiff\License`

**Describe alternatives you've considered**
No.

**Additional context**

**Comment by caroott** [comment]
Fixed in #6
